language: python

install: pip install tox

script:
- tox --recreate

deploy:
  provider: pypi
  user: jtpereyda
  password:
    secure: IfieokKKd+RXJCKz2lEglZb1C4DOdsKxsRd3fi3O3eMhthi12GTj6mkal7t/kTKOgiuI7qi8nqAlNEdNtMhOljy2TxX1C7nRHjOPObHU0WM5oXkQ+KLjzW5UG7TmjZ640ADlhP+G+lDStfb0v9C4TU4nQ5z86/8s203sxillws1VHYzL9+ZfV1qOTjxETLXHlkY50Z7EvSnorqBBHU+jYU5YjpLPvDd7ynERTiGmezjzpbbrB6TUrt+26YjsvWMhpsbBz0a6+CYQZb1oGABy4oGcV7zxUgKuZ3JcBYj69AMQDmHbvhh3k4R0qux5FXXjFiusbjP4QJgJcApTSgNHuAUNKW02otIwhVmDD5mTSkpAjqaT9WgxbYWjk4UE2a/LPhx1ZebJlHL6n3lkyfYsk4lADJhY97jFDLHghOMqVlqdJSdqJDLCfpKxREWJ+0jSpX5M77TkAmz1UfwT413UhVfhkOUDvtuSTACax2VbV90temFk0u4QvHKZvp9nrw6vcVjMHR5CtoeCwpoL5kPIH3D2vXclrmZNGv9au3CYzxjoAHEdtFd5ySAnRgfcW94Q/A00vqalPgeBGI7kL+2/1Ejm+kWml4vMeJMOMHeqrw7W7HjIXswAq+H+oNOxiXyH5lMcXVDjEd04MzTAeuYru8KB8S/CrmWGZpMwDYU7OG4=
  distributions: sdist bdist_wheel
  skip_cleanup: true
  on:
    tags: true
    repo: jtpereyda/defensics-pcap
    branch: master
